### ISSUE TITLE
[QA] Homepage > 'View the work' links don't work

### ISSUE THREAD

**Issue by jessicasheng15** [vigetlabs/npm#68] opened 2019-10-31 19:27 UTC
This could be a content entry thing where links haven't been entered yet. On the homepage, the 'View the work' links are not functioning.

https://www.dropbox.com/s/z8wma0kd2deh1a2/Screenshot%202019-10-31%2015.27.08.png?dl=0

**Comment by gracecanfield** [comment] 2019-11-01 14:29
Closing - this is a dupe of an existing ticket.

**Closed by gracecanfield** 2019-11-01 14:29 UTC
Labels: Bug, FED, High Priority
