### ISSUE TITLE
Quote block: Hide carousel arrows if only one testimonial exists

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#274] opened 2019-12-11 14:55 UTC
**Steps to Reproduce:**
1. Visit https://live-national-public-media-v2.pantheonsite.io/wp/wp-admin/post.php?post=182&action=edit. You'll see that only 1 testimonial has been added to the testimonial block at the bottom of the page.
2. Visit the front-end page - https://live-national-public-media-v2.pantheonsite.io/work/capitalone/
3. Expected: The quote block doesn't have any carousel arrows.
4. Actual: The carousel displays arrows ([screenshot of current](https://www.dropbox.com/s/j3s17m8ep16ckr3/Screenshot%202019-12-11%2009.53.53.png?dl=0))

**Task:**
* [x] Please update with conditional logic so the arrows are hidden if only one testimonial is present

**Comment by justinvandenberg** [comment] 2019-12-17 20:32
@gracecanfield I think this is a duplicate of #279 (or vice versa).

**Comment by gracecanfield** [comment] 2019-12-17 20:36
@justinvandenberg Sorry bout that!

**Closed** 2020-02-18 15:25 UTC
Labels: NPM Request, Needs QA Fixes
